# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import library_pb2 as library__pb2


class LibraryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBooks = channel.unary_stream(
                '/library.Library/ListBooks',
                request_serializer=library__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                )
        self.FilterBooks = channel.unary_stream(
                '/library.Library/FilterBooks',
                request_serializer=library__pb2.FilterBooksRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                )


class LibraryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBooks(self, request, context):
        """A server-to-client streaming RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FilterBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=library__pb2.ListBooksRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
            'FilterBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.FilterBooks,
                    request_deserializer=library__pb2.FilterBooksRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.Library', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Library(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/library.Library/ListBooks',
            library__pb2.ListBooksRequest.SerializeToString,
            library__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FilterBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/library.Library/FilterBooks',
            library__pb2.FilterBooksRequest.SerializeToString,
            library__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
