# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='library.proto',
  package='library',
  syntax='proto3',
  serialized_options=b'Z\010./protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rlibrary.proto\x12\x07library\x1a\x1egoogle/protobuf/wrappers.proto\"\x12\n\x10ListBooksRequest\"C\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12 \n\x07\x61uthors\x18\x03 \x03(\x0b\x32\x0f.library.Author\"\"\n\x06\x41uthor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"s\n\x12\x46ilterBooksRequest\x12+\n\x05title\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nauthorName\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\" \n\x1eSubscribeForBookUpdatesRequest2\xda\x01\n\x07Library\x12\x39\n\tListBooks\x12\x19.library.ListBooksRequest\x1a\r.library.Book\"\x00\x30\x01\x12=\n\x0b\x46ilterBooks\x12\x1b.library.FilterBooksRequest\x1a\r.library.Book\"\x00\x30\x01\x12U\n\x17SubscribeForBookUpdates\x12\'.library.SubscribeForBookUpdatesRequest\x1a\r.library.Book\"\x00\x30\x01\x42\nZ\x08./protosb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_LISTBOOKSREQUEST = _descriptor.Descriptor(
  name='ListBooksRequest',
  full_name='library.ListBooksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=76,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='library.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='library.Book.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='library.Book.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='authors', full_name='library.Book.authors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=145,
)


_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='library.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='library.Author.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='library.Author.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=181,
)


_FILTERBOOKSREQUEST = _descriptor.Descriptor(
  name='FilterBooksRequest',
  full_name='library.FilterBooksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='library.FilterBooksRequest.title', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='authorName', full_name='library.FilterBooksRequest.authorName', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=298,
)


_SUBSCRIBEFORBOOKUPDATESREQUEST = _descriptor.Descriptor(
  name='SubscribeForBookUpdatesRequest',
  full_name='library.SubscribeForBookUpdatesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=332,
)

_BOOK.fields_by_name['authors'].message_type = _AUTHOR
_FILTERBOOKSREQUEST.fields_by_name['title'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_FILTERBOOKSREQUEST.fields_by_name['authorName'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
DESCRIPTOR.message_types_by_name['ListBooksRequest'] = _LISTBOOKSREQUEST
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
DESCRIPTOR.message_types_by_name['FilterBooksRequest'] = _FILTERBOOKSREQUEST
DESCRIPTOR.message_types_by_name['SubscribeForBookUpdatesRequest'] = _SUBSCRIBEFORBOOKUPDATESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListBooksRequest = _reflection.GeneratedProtocolMessageType('ListBooksRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTBOOKSREQUEST,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.ListBooksRequest)
  })
_sym_db.RegisterMessage(ListBooksRequest)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.Book)
  })
_sym_db.RegisterMessage(Book)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.Author)
  })
_sym_db.RegisterMessage(Author)

FilterBooksRequest = _reflection.GeneratedProtocolMessageType('FilterBooksRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILTERBOOKSREQUEST,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.FilterBooksRequest)
  })
_sym_db.RegisterMessage(FilterBooksRequest)

SubscribeForBookUpdatesRequest = _reflection.GeneratedProtocolMessageType('SubscribeForBookUpdatesRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEFORBOOKUPDATESREQUEST,
  '__module__' : 'library_pb2'
  # @@protoc_insertion_point(class_scope:library.SubscribeForBookUpdatesRequest)
  })
_sym_db.RegisterMessage(SubscribeForBookUpdatesRequest)


DESCRIPTOR._options = None

_LIBRARY = _descriptor.ServiceDescriptor(
  name='Library',
  full_name='library.Library',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=335,
  serialized_end=553,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListBooks',
    full_name='library.Library.ListBooks',
    index=0,
    containing_service=None,
    input_type=_LISTBOOKSREQUEST,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FilterBooks',
    full_name='library.Library.FilterBooks',
    index=1,
    containing_service=None,
    input_type=_FILTERBOOKSREQUEST,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeForBookUpdates',
    full_name='library.Library.SubscribeForBookUpdates',
    index=2,
    containing_service=None,
    input_type=_SUBSCRIBEFORBOOKUPDATESREQUEST,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIBRARY)

DESCRIPTOR.services_by_name['Library'] = _LIBRARY

# @@protoc_insertion_point(module_scope)
